### PR TITLE
Fixed save button issue

### LINKED ISSUE #69: BUG - log screen save button jumps
When clicking on "save" in log screen the green button jumps up as it returns to the calendar

https://user-images.githubusercontent.com/75044178/222794461-49747e50-60cb-4339-b584-5a253ba2b6cb.mov

### PR DESCRIPTION
**Pull request by PierreLessard**
Had a short eureka moment that the issue with the save button was the bottom navigation composing early and messing up the scaffold. So instead I moved the bottom navigation within the box and now it composes fine. This messed up the inner padding so I had to hardcode parts of the padding so that the Fab and logging options were still in line.

### CODE REVIEW

File: app/src/main/java/com/tpp/theperiodpurse/ui/calendar/CalendarScreen.kt [hunk 1]
```diff
@@ -227,7 +227,7 @@ fun CalendarScreenLayout(
                     modifier = Modifier
                         .padding(horizontal = 12.dp)
                         .semantics { contentDescription = "Calendar" },
-                    contentPadding = PaddingValues(bottom = 48.dp),
+                    contentPadding = PaddingValues(bottom = 66.dp),
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/calendar/CalendarScreen.kt]: Can you change this to 120? Just for the sake of appearence

**Review by leowrites — APPROVED** [review]

File: app/src/main/java/com/tpp/theperiodpurse/ui/calendar/CalendarScreen.kt (hunk 1 above)
Comment (PierreLessard) [reply app/src/main/java/com/tpp/theperiodpurse/ui/calendar/CalendarScreen.kt]: I agree, done
