### PR TITLE
fixed bug where user doesn't give permission to all google drive scopes

### LINKED ISSUE #164: BUG - UserRecoverableAuthIOException
When the user does not give consent to required permissions, the app crashes
```
Exception com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException:
  at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept (GoogleAccountCredential.java:297)
  at com.google.api.client.http.HttpRequest.execute (HttpRequest.java:868)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed (AbstractGoogleClientRequest.java:419)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed (AbstractGoogleClientRequest.java:352)
  at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute (AbstractGoogleClientRequest.java:469)
  at com.tpp.theperiodpurse.ui.viewmodel.OnboardViewModel$checkGoogleDrive$1$1.invokeSuspend (OnboardViewModel.kt:89)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.internal.LimitedDispatcher.run (LimitedDispatcher.kt:42)
  at kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:95)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)
Caused by com.google.android.gms.auth.UserRecoverableAuthException: NeedRemoteConsent
  at com.google.android.gms.auth.zzl.zzg (com.google.android.gms:play-services-auth-base@@18.0.4:20)
  at com.google.android.gms.auth.zzl.zzb (com.google.android.gms:play-services-auth-base@@18.0.4:4)
  at com.google.android.gms.auth.zzf.zza
  at com.google.android.gms.auth.zzl.zzh (com.google.android.gms:play-services-auth-base@@18.0.4:6)
  at com.google.android.gms.auth.zzl.zza (com.google.android.gms:play-services-auth-base@@18.0.4:15)
  at com.google.android.gms.auth.zzl.getToken (com.google.android.gms:play-services-auth-base@@18.0.4:3)
  at com.google.android.gms.auth.zzl.getToken (com.google.android.gms:play-services-auth-base@@18.0.4:1)
  at com.google.android.gms.auth.zzl.getToken (com.google.android.gms:play-services-auth-base@@18.0.4:6)
  at com.google.android.gms.auth.GoogleAuthUtil.getToken (com.google.android.gms:play-services-auth-base@@18.0.4:3)
  at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken (GoogleAccountCredential.java:267)
  at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept (GoogleAccountCredential.java:292)
```

### PR DESCRIPTION
**Pull request by kevinle623**
https://github.com/uoftblueprint/the-period-purse-2023/assets/74465053/83ba13b4-535e-4ceb-8fff-5d105bc02862

### CODE REVIEW

File: app/src/main/java/com/tpp/theperiodpurse/ui/onboarding/DownloadBackup.kt [hunk 1]
```diff
@@ -29,9 +32,24 @@ fun DownloadBackup(
...
+            if (!confirmLoad.value) {
+                Toast.makeText(context, "ERROR - Please grant all the required permissions", Toast.LENGTH_SHORT).show()
+                signout()
+                LaunchedEffect(Unit) {
+                    viewModel.isDownloaded.postValue(null)
+                    navHostController.popBackStack(OnboardingScreen.Welcome.name, inclusive = true)
+                    navHostController.navigate(OnboardingScreen.Welcome.name)
+                }
+            }
+        }
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/onboarding/DownloadBackup.kt]: Need better naming here, what is the difference between isDownloaded and confirmLoad? Also can we move this so that we don't navigate here in the first place if no permissions?

File: app/src/main/java/com/tpp/theperiodpurse/ui/onboarding/LoadGoogleDrive.kt [hunk 2]
```diff
@@ -37,79 +40,91 @@ fun LoadGoogleDrive(
...
-                navHostController.navigate(OnboardingScreen.QuestionOne.name)
+        } else if (isDriveSafe != null){
+            Toast.makeText(context, "ERROR - Please grant all the required permissions", Toast.LENGTH_SHORT).show()
+            signout()
+            if (!confirmLoad.value) {
+                LaunchedEffect(Unit) {
+                    navHostController.popBackStack(OnboardingScreen.Welcome.name, inclusive = true)
+                    navHostController.navigate(OnboardingScreen.Welcome.name)
+                }
+                confirmLoad.value = true
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/onboarding/LoadGoogleDrive.kt]: Instead of navigating to LoadGoogleDrive and going back to welcome, can we just not navigate user in the first place?

File: app/src/main/java/com/tpp/theperiodpurse/ui/setting/BackupDatabase.kt [hunk 3]
```diff
@@ -34,13 +37,24 @@ fun BackupDatabase(viewModel: OnboardViewModel,
...
-            viewModel.isBackedUp.postValue(null)
-            navController.navigate(SettingScreenNavigation.ConfirmBackup.name)
-
+        if (isBackedUp == true) {
+            LaunchedEffect(Unit){
+                viewModel.isBackedUp.postValue(null)
+                navController.navigate(SettingScreenNavigation.ConfirmBackup.name)
+            }
+        } else {
+            if (!confirmLoad.value){
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/setting/BackupDatabase.kt]: What is confirmLoad?

File: app/src/main/java/com/tpp/theperiodpurse/ui/viewmodel/OnboardViewModel.kt [hunk 4]
```diff
@@ -113,75 +85,125 @@ class OnboardViewModel @Inject constructor (
...
                         .setSpaces("appDataFolder").execute()
 
-                    val fileId = fileList.files[0].id
-
-                    val outputStream = ByteArrayOutputStream()
-
-                    drive.files().get(fileId).executeMediaAndDownloadTo(outputStream)
 
-                    val data = outputStream.toByteArray()
+                    isDrive.postValue(googleDriveFolder)
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/viewmodel/OnboardViewModel.kt]: isDrive can also use better naming, maybe just `googleDriveFolder`?

File: app/src/main/java/com/tpp/theperiodpurse/ui/viewmodel/OnboardViewModel.kt [hunk 5]
```diff
@@ -113,75 +85,125 @@ class OnboardViewModel @Inject constructor (
...
+                    isDriveSafe.postValue(null)
+                } catch (e: Exception) {
+                    isDrive.postValue(null)
+                    isDriveSafe.postValue(true)
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/viewmodel/OnboardViewModel.kt]: In case an exception happens, you should probably log what the exception is

File: app/src/main/java/com/tpp/theperiodpurse/ui/viewmodel/OnboardViewModel.kt [hunk 6]
```diff
@@ -113,75 +85,125 @@ class OnboardViewModel @Inject constructor (
...
+
+                        FileOutputStream(dbFilePath).apply {
+                            write(data)
+                            flush()
+                            close()
+                        }
+
+                        isDownloaded.postValue(true)
+                    } catch (e: java.lang.Exception) {
+                        isDownloaded.postValue(false)
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/ui/viewmodel/OnboardViewModel.kt]: Similar here, at least log the exception

File: app/src/main/java/com/tpp/theperiodpurse/AppScreen.kt [hunk 7]
```diff
@@ -204,6 +204,7 @@ fun ScreenApp(
     hasNotificationsPermissions: Boolean = false,
 
     ) {
+    signout()
```
Comment (leowrites) [inline app/src/main/java/com/tpp/theperiodpurse/AppScreen.kt]: This is signing the user out every time the app opens. All of these really should be handled in a place like `handleSignInResult` or in `WelcomeScreen` when it detects an account before navigating away. The logic should be:
User in `WelcomeScreen` and tries to sign in. 
- If fails(either did not sign in or try Google Drive and fails) revoke signout & revoke access, give a corresponding toast and do nothing else
- If success navigate to next page
Currently `signout` is called when user tries to ***use*** Google drive, but user should not have the option to use Google Drive unless they are signed in.

**Review by leowrites — CHANGES_REQUESTED** [review]

**Comment by leowrites** [comment]
Tests are failing may be because previous `AppViewModel.loadData` was running all of the database queries in `Dispatcher.Main`, which was blocking the UI thread and it's supposed to be in `Dispatcher.IO`. So need to figure out how to make the tests wait for loading to complete before continuing

**Comment by leowrites** [comment]
All tests under` CalendarCycleTabTest` are failing

The problem is where `databaseIsLoadedFromStorage.postValue(true)` is placed in `AppViewModel`. Before it is placed outside of the view model so it's executed immediately and the UI is not actually showing the loading screen when waiting to fetch database. 

This caused the tests to fail because after properly using async operations (and I moved `databaseIsLoadedFromStorage.postValue(true)` to ***after*** the fetching operation is complete), the tests are not waiting for the loading to complete and tried to navigate around when it's still showing the loading screen. 

For this patch, I will update `databaseIsLoadedFromStorage` immediately when `AppViewModel.loadData` is called to make the tests pass, but the tests needs to be fixed either to 
1. Wait for asynchronous loading to complete
2. Jump over the loading screen to the calendar screen immediately
